// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A YouTube comment sentiment analyzer.
 *
 * - analyzeSentiment - A function that handles the sentiment analysis of YouTube comments.
 * - AnalyzeSentimentInput - The input type for the analyzeSentiment function.
 * - AnalyzeSentimentOutput - The return type for the analyzeSentiment function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeSentimentInputSchema = z.object({
  videoUrl: z.string().describe('The URL of the YouTube video to analyze.'),
});
export type AnalyzeSentimentInput = z.infer<typeof AnalyzeSentimentInputSchema>;

const AnalyzeSentimentOutputSchema = z.object({
  overallSentiment: z
    .string()
    .describe('The overall sentiment of the comments (positive, negative, or neutral).'),
  positiveKeywords: z
    .string()
    .describe('Key positive keywords extracted from the comments.'),
  negativeKeywords: z
    .string()
    .describe('Key negative keywords extracted from the comments.'),
});
export type AnalyzeSentimentOutput = z.infer<typeof AnalyzeSentimentOutputSchema>;

export async function analyzeSentiment(input: AnalyzeSentimentInput): Promise<AnalyzeSentimentOutput> {
  return analyzeSentimentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeSentimentPrompt',
  input: {schema: AnalyzeSentimentInputSchema},
  output: {schema: AnalyzeSentimentOutputSchema},
  prompt: `Analyze the sentiment of the YouTube video comments from the following URL: {{{videoUrl}}}. Determine the overall sentiment (positive, negative, or neutral), extract key positive keywords, and extract key negative keywords.

Overall Sentiment:
Positive Keywords:
Negative Keywords:`, 
});

const analyzeSentimentFlow = ai.defineFlow(
  {
    name: 'analyzeSentimentFlow',
    inputSchema: AnalyzeSentimentInputSchema,
    outputSchema: AnalyzeSentimentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
